apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  JwtKey: WW91clZlcnlTZWN1cmVBbmRMb25nS2V5VGhhdElzQXRMZWFzdDMyQnl0ZXNMb25n
  JwtIssuer: eW91cl9pc3N1ZXJfaGVyZQ==
  JwtAudience: eW91cl9hdWRpZW5jZV9oZXJl
