apiVersion: v1
kind: Service
metadata:
  name: movieservice-srv
spec:
  type: NodePort
  selector:
    app: movieservice
  ports:
    - name: movieservice
      protocol: TCP
      port: 80
      targetPort: 80