apiVersion: v1
kind: Service
metadata:
  name: movieservice-nodeport-srv
spec:
  type: NodePort
  selector:
    app: movieservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001