apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  RabbitMQHost: cmFiYml0bXEtY2x1c3RlcmlwLXNydg==
  RabbitMQPort: NTY3Mg==
  RabbitMQUsername: Z3Vlc3Q=
  RabbitMQPassword: Z3Vlc3Q=