apiVersion: batch/v1
kind: Job
metadata:
  name: reviewservice-job-db-migration
spec:
  template:
    spec:
      containers:
      - name: job-db-migration
        image: vladockerhub/reviewservice:latest
        command: ["dotnet", "ef", "database", "update"]
        env:
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JwtKey
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JwtIssuer
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JwtAudience
        - name: RabbitMQ__Host
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RabbitMQHost
        - name: RabbitMQ__Port
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RabbitMQPort
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RabbitMQUsername
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RabbitMQPassword
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: reviewservice-db-connection-secrets
              key: ConnectionStringsDefaultConnection
      restartPolicy: OnFailure
