apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
        - name: reviewservice
          image: vladockerhub/reviewservice:latest
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtKey
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtIssuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtAudience
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQHost
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQPort
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQUsername
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQPassword
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: review-service-secrets
                  key: ConnectionStringsDefaultConnection
---
apiVersion: v1
kind: Secret
metadata:
  name: review-service-secrets
type: Opaque
data:
  ConnectionStringsDefaultConnection: RGF0YSBTb3VyY2U9REVTS1RPUC1PNVBBOUxCXFxTUUxFWFBSRVNTO0luaXRpYWwgQ2F0YWxvZz1SZXZpZXdEYjtJbnRlZ3JhdGVkIFNlY3VyaXR5PVRydWU7Q29ubmVjdCBUaW1lb3V0PTMwO0VuY3J5cHQ9RmFsc2U7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1GYWxzZTtBcHBsaWNhdGlvbkludGVudD1SZWFkV3JpdGU7TXVsdGlTdWJuZXRGYWlsb3Zlcj1GYWxzZQ==
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: reviewservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080