apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: vladockerhub/userservice:latest
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtKey
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtIssuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: JwtAudience
            - name: RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQHost
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQPort
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQUsername
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: RabbitMQPassword
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: ConnectionStringsDefaultConnection
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  ConnectionStringsDefaultConnection: RGF0YSBTb3VyY2U9REVTS1RPUC1PNVBBOUxCXFxTUUxFWFBSRVNTO0luaXRpYWwgQ2F0YWxvZz1Vc2Vyc0RiO0ludGVncmF0ZWQgU2VjdXJpdHk9VHJ1ZTtDb25uZWN0IFRpbWVvdXQ9MzA7RW5jcnlwdD1GYWxzZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0FwcGxpY2F0aW9uSW50ZW50PVJlYWRXcml0ZTtNdWx0aVN1Ym5ldEZhaWxvdmVyPUZhbHNl
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080